--- #YAML:1.0
name:                HTTP-Cookies-Safari
version:             1.13
abstract:            Cookie storage and management for Safari
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Date::Calc:                    0
    HTTP::Cookies:                 1.25
    Mac::PropertyList:             0.9
    Text::Diff:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
