--- #YAML:1.0
name:               HTTP-Cookies-Safari
version:            1.14
abstract:           Cookie storage and management for Safari
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Calc:         0
    HTTP::Cookies:      1.25
    Mac::PropertyList:  1.33
    Text::Diff:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
